# Generated by Django 5.2.8 on 2025-11-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
